# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import secret_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=25, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=25, validators=[secret_page.models.validate_word]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=25, validators=[secret_page.models.validate_word]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=25, validators=[secret_page.models.validate_password]),
        ),
    ]
